### ISSUE TITLE
Missing config.yaml file

### ISSUE THREAD

**Issue by janithwanni** [deephdc/posenet-tf#1]
I'm planning on using the posenet implementation on TensorFlow for a project of mine. The 'posenetclas' is the folder i extracted and decided to use by feeding a webcam input to the model. (Correct me if I'm wrong here, I'm still a newbie in Machine Learning. It is a bit time consuming for me to implement the research paper from scratch or to convert from tfjs from scratch) 
After I got the folder setup properly I noticed that the config.py requires a yaml file in the etc folder of the home dir (project root i believe) . This config.yaml is quite different from the one inside the converter as I tried plugging the file in the converter to path that was needed. 
Any help would be appreciated

**Comment by laramaktub** [comment]
Hi Janith,

I am not sure I understand the issue. The config  file in /etc is used in an API in order to launch everything from the web browser. https://github.com/deephdc/DEEP-OC-posenet-tf
If you are not using the API you don't need that config.yaml. 

The config.yaml in converter is the one you can find in: https://github.com/deephdc/posenet-tf/blob/master/posenetclas/converter/config.yaml

**Comment by janithwanni** [comment]
Oh now I understood the problem. Thank you very much for the feedback. So if I was to use this repo as a standalone desktop application then I don't have to worry about the config.yaml file in etc that is used for the API right?
